### ISSUE TITLE
Warnings in Erlang/OTP 27

### ISSUE THREAD

**Issue by AdSkipper1337** [everzet/text_delta#6]
Hi! I am using your library and after updating to OTP27 I started getting warnings because of deprecations:

```
iex(1)> warning: negative steps are not supported in Enum.slice/2, pass 0..-2//1 instead
  (elixir 1.17.3) lib/enum.ex:3000: Enum.slice/2
  (text_delta 1.4.0) lib/text_delta.ex:207: TextDelta.trim/1
  (text_delta 1.4.0) lib/text_delta/difference.ex:64: TextDelta.Difference.diff/2
  (text_delta 1.4.0) lib/text_delta/difference.ex:81: TextDelta.Difference.diff!/2
  (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
```
The project hasn't seen updates in years now... I would like to offer to fix this and also contribute to maintaining the package in the future since I am using it in production and I am quite familiar with how it works at this point.

For that it would really help if someone is still arround to merge changes and for me to work with, which is why I am opening the issue. 

Best

**Comment by everzet** [comment]
I think safer bet at this point would be for you to to fork it.
